// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsbaCwK_bclNQq9H3Hf2F7DtJX3ejOJDY',
    appId: '1:548161049509:web:5a5b1b618fe49023014e4c',
    messagingSenderId: '548161049509',
    projectId: 'mapguaru-dart',
    authDomain: 'mapguaru-dart.firebaseapp.com',
    storageBucket: 'mapguaru-dart.firebasestorage.app',
    measurementId: 'G-VMQ6NQNJ6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOUuIDiTApe607zO4bu2mELqWiEzq5x8w',
    appId: '1:548161049509:android:cfa888cc901072c1014e4c',
    messagingSenderId: '548161049509',
    projectId: 'mapguaru-dart',
    storageBucket: 'mapguaru-dart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq5udfF8YzEJM6OL_g5UblEeu7xmGJH1k',
    appId: '1:548161049509:ios:26a5e64f30bb9720014e4c',
    messagingSenderId: '548161049509',
    projectId: 'mapguaru-dart',
    storageBucket: 'mapguaru-dart.firebasestorage.app',
    iosClientId: '548161049509-0pvqg2fe5cs8rh14e316qtd3o7vqdink.apps.googleusercontent.com',
    iosBundleId: 'com.mapguaru.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq5udfF8YzEJM6OL_g5UblEeu7xmGJH1k',
    appId: '1:548161049509:ios:26a5e64f30bb9720014e4c',
    messagingSenderId: '548161049509',
    projectId: 'mapguaru-dart',
    storageBucket: 'mapguaru-dart.firebasestorage.app',
    iosClientId: '548161049509-0pvqg2fe5cs8rh14e316qtd3o7vqdink.apps.googleusercontent.com',
    iosBundleId: 'com.mapguaru.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsbaCwK_bclNQq9H3Hf2F7DtJX3ejOJDY',
    appId: '1:548161049509:web:00256afa253b5c28014e4c',
    messagingSenderId: '548161049509',
    projectId: 'mapguaru-dart',
    authDomain: 'mapguaru-dart.firebaseapp.com',
    storageBucket: 'mapguaru-dart.firebasestorage.app',
    measurementId: 'G-64497F1SBF',
  );

}